apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.environment }}
  name: hello
spec:
  type: {{ .Values.loadbalancer.type }}
  ports:
    - port: {{ .Values.port }}
      # targetPort: {{ .Values.port }}
  selector:
    name: {{ .Chart.Name }}
